-
  name: 单项经营能力熵值分析
  request:
   method: post
   url: /qitan-company-data/management/industryMsConfig
   header:
    Content-Type: application/x-www-form-urlencoded
   data:
    orgCode:
    endDate: